refactor: interface
CGI-FR/RIMO pull request #29
Opened 2023-08-28 17:37 UTC by mathisdrn

2023-08-31 08:58 UTC, youen requested changes

2023-08-31 08:58 UTC, youen commented on internal/infra/infra_test.go
> +package infra_test
licence

2023-08-31 08:58 UTC, youen commented on internal/infra/infra_test.go
> +// var (
à supprimer

2023-08-31 08:58 UTC, youen commented on pkg/model/column.go
> +package model
licence

2023-08-31 08:58 UTC, youen commented on pkg/rimo/driver.go
> +package rimo
licence

2023-08-31 08:58 UTC, youen commented on test/suites/testdata/data1/output/data.yaml
>              empty: 0
doit etre dans le gitignore (en conflit avec main)

2023-08-31 11:42 UTC, mathisdrn commented
Prochaines étapes :
- S'assurer que les tests de analyse_test.go soit reproduit dans driver.go 
- S'assurer que les tests de /io/load_test et /io/export_test soit reproduit dans infra/_test.go
- Supprimer pkg/analyse; remplacé par driver.go 
- Supprimer pkg/io/: remplacé par infra/
- Mettre à jour la commande RIMO pour utiliser l'implémentation FilesReader() et FileWriter()
 - Réécrire les benchmarks à partir d'une implémentation -> de analyse_test.go à infra_test.go

2023-08-31 11:49 UTC, mathisdrn commented
Bug discovery :
La fonction SetNumericMetric ne gère que les variable float64.

Warn : les implémentations TestReader et LINOReader sont suceptibles d'envoyer des numériques autres que float64()

Solutions : 
- usage des generiques :
    1. à l'échelle de SetNumericMetric pour définir []T avec T contains [int, int64, float64, uint] etc... et faire une assertion de type avec le type générique Numeric 
    2. à l'échelle du point d'entrée des données à l'aide de LINO ou d'une fonction pour FilesReader

2023-08-31 13:35 UTC, mathisdrn commented
TODO make column values []interface{} given as a pointer within interface

2023-08-31 13:38 UTC, mathisdrn commented
INFO : rimo -> moved to model again to circular dependencies :
- metric depends on model.go to know column definitions
- driver.go depends on metric to call computeMetric()
=> model.go and driver.go cannot be in same package

2023-09-15 07:52 UTC, mathisdrn commented
Très probablement mon dernier commit sur RIMO.

Les interfaces sont implémentés, les tests passent.

À noter : les tests unitaires avec comparaisons ne produisent plus de fichier de sortie (voir TestWriter{} et dernier commit si cela doit être réimplémenter)

Prochaines étapes pour push la MR :
- supprimer les packages : io, analyse
- supprimer l'ancienne commande 'rimo analyse'
- renommer rimo analyse2 par rimo analyse
- ajouter les licences

2023-09-27 20:33 UTC, youen approved these changes

2023-09-27 20:34 UTC, youen approved these changes

2023-09-27 20:43 UTC, merged

2023-09-27 20:45 UTC, youen commented
Merci beaucoup @mathisdrn pour ton implication dans le projet RIMO et plus généralement dans la solution LINO !

2023-09-30 13:34 UTC, mathisdrn commented
Merci de même @youen pour ton support et tes conseils !